# Generated by Django 2.2.14 on 2020-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=100)),
                ('tipo_cancha', models.CharField(max_length=80)),
                ('vestuario', models.BooleanField(default=False)),
                ('iluminacion', models.BooleanField(default=False)),
                ('cesped_sintetico', models.BooleanField(default=False)),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
            },
        ),
    ]
