# Generated by Django 2.2.14 on 2020-08-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='ruta_imagen',
            field=models.FileField(blank=True, default='defecto/defecto.jpg', null=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
