# Generated by Django 2.2.14 on 2020-08-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_cancha_ruta_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ['-fecha_create'], 'verbose_name': 'cancha', 'verbose_name_plural': 'canchas'},
        ),
        migrations.AlterField(
            model_name='cancha',
            name='cesped_sintetico',
            field=models.BooleanField(default=False, verbose_name='Tipo de Cesped'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='codigo_interno',
            field=models.CharField(max_length=100, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='fecha_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creacion'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='iluminacion',
            field=models.BooleanField(default=False, verbose_name='Iluminacion'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='ruta_imagen',
            field=models.FileField(blank=True, default='defecto/defecto.jpg', null=True, upload_to='fotos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='tipo_cancha',
            field=models.CharField(max_length=80, verbose_name='Tipo de Cancha'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='vestuario',
            field=models.BooleanField(default=False, verbose_name='Vestuario'),
        ),
    ]
