# Generated by Django 2.2.14 on 2020-08-31 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0003_auto_20200831_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('empleado', models.CharField(max_length=100, verbose_name='Empleado de turno')),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_turno', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Reserva')),
                ('hora_turno', models.TimeField(verbose_name='Hora de Reserva')),
                ('cancha', models.ManyToManyField(to='canchas.Cancha', verbose_name='Cancha')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-fecha_create'],
            },
        ),
    ]
