# Generated by Django 2.2.14 on 2020-08-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_turno',
            field=models.DateField(verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
