# Generated by Django 2.2.14 on 2020-09-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_auto_20200901_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_interno', models.CharField(max_length=100, verbose_name='Codigo')),
                ('tipo_cancha', models.CharField(max_length=80, verbose_name='Tipo de Cancha')),
                ('vestuario', models.BooleanField(default=False, verbose_name='Vestuario')),
                ('iluminacion', models.BooleanField(default=False, verbose_name='Iluminacion')),
                ('cesped_sintetico', models.BooleanField(default=False, verbose_name='Tipo de Cesped')),
                ('ruta_imagen', models.FileField(blank=True, default='defecto/defecto.jpg', null=True, upload_to='fotos/%Y/%m/%d', verbose_name='Imagen')),
                ('fecha_create', models.DateTimeField(auto_now_add=True, verbose_name='Creacion')),
                ('fecha_update', models.DateTimeField(auto_now=True, verbose_name='Update')),
            ],
            options={
                'verbose_name': 'cancha',
                'verbose_name_plural': 'canchas',
                'ordering': ['-fecha_create'],
            },
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ManyToManyField(to='reservas.Cancha2', verbose_name='Cancha'),
        ),
    ]
