# Generated by Django 2.2.14 on 2020-09-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20200901_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancha2',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ManyToManyField(to='canchas.Cancha', verbose_name='Cancha'),
        ),
    ]
