# Generated by Django 2.2.14 on 2020-09-01 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20200901_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cancha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancha',
            field=models.TextField(default=django.utils.timezone.now, max_length=100, verbose_name='Cancha'),
            preserve_default=False,
        ),
    ]
