# Generated by Django 2.2.14 on 2020-09-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20200901_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.CharField(max_length=100, verbose_name='Cancha'),
        ),
    ]
